# Generated by Django 5.0.8 on 2026-01-22 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_post_doctor_awards_doctor_certifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkup',
            name='currency',
            field=models.CharField(default='UZS', max_length=10),
        ),
        migrations.AddField(
            model_name='checkup',
            name='duration_ru',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='checkup',
            name='duration_uz',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='checkup',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='checkups/icons/'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='price_unit_ru',
            field=models.CharField(default='пакет', max_length=50),
        ),
        migrations.AddField(
            model_name='checkup',
            name='price_unit_uz',
            field=models.CharField(default='paket', max_length=50),
        ),
        migrations.AddField(
            model_name='checkup',
            name='target_ru',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='checkup',
            name='target_uz',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='price',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CheckupBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_uz', models.CharField(max_length=255)),
                ('title_ru', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('checkup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='main.checkup')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckupTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_uz', models.CharField(max_length=255)),
                ('title_ru', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('checkup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='main.checkup')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
